match order with prompts
pankod/superplate pull request #201
Opened 2021-02-04 14:01 UTC by aliemir

Resolves #189

2021-02-04 14:15 UTC, mhrrmk approved these changes

2021-02-04 21:40 UTC, burcukaragozzz requested changes

2021-02-05 06:35 UTC, omeraplak approved these changes

2021-02-05 06:36 UTC, aliemir commented
#pr-ready

2021-02-05 06:36 UTC, merged